### ISSUE TITLE
Receiving Error Message When Trying to Activate on Mac

### ISSUE THREAD

**Issue by FlexiSPY-Feedback** [FlexiSPY/flexispy-desktop-beta-testing#5]
### Steps to reproduce bug
1. Open FlexiSPY Desktop version 1.0.2 on MacBook Pro 
2. Attempt to activate with activation code

**Expected behavior:** FlexiSPY Desktop should activate
**Actual behavior:** An error message appears saying 'Unstructured response is not ok'
### Discussion:

I have followed the steps and removed the Flexispy, restarted the computer and did install it again. However, when I try to activate I get an error message (as you can see in the attached screenshot)? 
Any suggestions?

**FlexiSPY Desktop V 1.0.2**

(Operating System: Intel Core 2Duo MacBook Pro (2008 Model) running OS X 10.10.5 (Yosemite)
![2016-09-02-21 32 30](https://cloud.githubusercontent.com/assets/21357541/18246275/dbd08696-7394-11e6-8284-2d0a3f2dbae6.jpg)

**Comment by Dee2009** [comment]
Even after uninstall and reinstall (a few times) still get the same response. Computer is connected to internet. Maybe related to second time activation?

**Comment by Dakota-FlexiSPY** [comment]
Hey @Dee2009 - Our developers are still looking into this but in the meantime I've gone ahead and sent you another license code. Please try and install and active with the new license code and let me know if it's successful or not.

**Comment by Dee2009** [comment]
Thanks. By the way, did not recieved the new license code yet. Will try as soon as I get it.

**Comment by Dee2009** [comment]
Even after fresh install and new license code, the problem still exists. Sent the log file via PM. Seems like a permission issue to me.

**Comment by Dakota-FlexiSPY** [comment]
@Dee2009 We have received your log file, thanks for sending it over. Also, we will send you an update as soon as we know more.

**Comment by Dakota-FlexiSPY** [comment]
Hi @Dee2009 

Regarding the license activation issue: our development team believe that the software might not be installed as an admin. Could you check if that's the issue?

If that doesn't work, would you be ok with installing TeamViewer and we can remote to help resolve the issue ?

**Comment by Dee2009** [comment]
Hi Dakota,

It is not admin issues. There are two admin accounts and I tried them both. I will install TeamViewer and send the login details via PM.

**Comment by Dakota-FlexiSPY** [comment]
@Dee2009 The issue is fixed and your license is now active 😄

**Comment by Dee2009** [comment]
Yes it seems it is working fine. Thank you very much!
